ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - prisma

onlyBuiltDependencies:
  - better-sqlite3

patchedDependencies:
  better-auth@1.3.7: patches/better-auth@1.3.7.patch
  drizzle-kit@0.31.4: patches/drizzle-kit@0.31.4.patch
